services:
  enshrouded:
    image: tsxcloud/enshrouded-arm:latest
    ports:
      - "15637:15637/udp"
      - "15638:15638/udp"
    volumes:
      - ./enshrouded/server:/mnt/enshrouded/server
      - ./enshrouded/persistentdata:/mnt/enshrouded/persistentdata
    restart: unless-stopped
    network_mode: bridge
    #This is required for ntsync to work inside Docker.
    #If ntsync support is not enabled in your Linux kernel, comment out this section, otherwise Docker Compose won't start.
#   devices:
#     - /dev/ntsync:/dev/ntsync


